import styles from './layout.module.scss'
import Head from 'next/head'
import Nav from './Nav'


export default function Layout(props){
    return(
        <div className={styles.layout}>
            <Head>
                <title>109下||期末project</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/magpie.svg" />
            </Head>

            <Nav/>
            
            <main className={styles.main}>{props.children}</main>

            

        </div>
    )
}